- name: Install and configure basics for a new Ubuntu VM
  hosts: 
    test1
  user: ubuntu
  become: true
  tasks:
  - name: Install good to have software and dependencies
    apt: 
      update_cache: yes
      state: latest
      name:
        byobu,
        python3-pip,
        git,
        nmon

  - name: configure byobu launch-by-default
    shell: printf "\n_byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true" >> /home/ubuntu/.profile

  - name: Copy bashrc file to new VM
    copy:
      src: ~/.bashrc
      dest: /home/ubuntu/
