- name: Install ansible on the remote host
  hosts: 
    test1
  user: ubuntu
  become: true
  tasks:
  - name: install pip
    apt:
      name:
        python3-pip

  - name: install ansible and openstacksdk
    pip:
      name:
        ansible==2.9.2,
        openstacksdk
