- name: Set up compute
  hosts: 
    test1
  user: ubuntu
  become: yes
  tasks:
    - name: set keystone credentials
      include_vars:
        file: clouds.yml
        name: os_auth

    - name: install pip
      apt:
        update_cache: yes
        force_apt_get: yes
        name:
          python3-pip

# This is necessary on the VM for os_server_volume to work
    - name: install openstacksdk
      pip:
        name:
          openstacksdk

# This attaches an already existing volume to the VM
    - name: attach volume to host
      os_server_volume:
        auth: "{{ os_auth }}"
        state: present
        server: Testing
        region_name: bgo
        volume: test
        device: /dev/sdc

    - name: mount /dev/sdc on /media/
      mount:
        path: /media/
        src: /dev/sdc
        fstype: ext4
        opts: rw,noauto
        state: mounted

# This one is only useful if you have made a new drive when you created the VM (e.g with terraform)
    - name: Create filesystem on /dev/sdb
      filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: mount /dev/sdb on ~/secondDrive
      mount:
        path: /home/ubuntu/secondDrive
        src: /dev/sdb
        fstype: ext4
        opts: rw,noauto
        state: mounted
